sudo: false
cache: cargo
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo --version
  - rustc --version
  - cargo build --verbose
  # Test using all possible feature combinations, keep in sync with AppVeyor.
  - cargo test --verbose --all --all-features
  - cargo test --verbose --all --no-default-features
  # Stress test.
  - cargo test --verbose --all-features -- --ignored
